export interface OpportunityItem {
  id: string;
  slug: string;
  titleFr: string;
  titleEn: string;
  titleAr: string;
  category: "SCHOLARSHIP" | "FELLOWSHIP" | "GRANT" | "EMERGENCY_FUND";
  degreeLevel: "UNDERGRADUATE" | "MASTER" | "PHD" | "POSTDOC" | "ALL";
  country: string;
  hostInstitution: string;
  deadline: string;
  coverageFr: string;
  coverageEn: string;
  coverageAr: string;
  descriptionFr: string;
  descriptionEn: string;
  descriptionAr: string;
  officialUrl: string;
  isFeatured?: boolean;
}

export const opportunitiesList: OpportunityItem[] = [
  // --- NIVEAU LICENCE / UNDERGRADUATE ---
  {
    id: "turkiye-burslari-licence-2026",
    slug: "bourses-gouvernement-turc-licence-2026",
    titleFr: "Bourses du Gouvernement Turc (Türkiye Bursları) - Premier Cycle",
    titleEn: "Türkiye Scholarships Undergraduate Program 2026-2027",
    titleAr: "منح الحكومة التركية لمرحلة البكالوريوس 2026-2027",
    category: "SCHOLARSHIP",
    degreeLevel: "UNDERGRADUATE",
    country: "Turquie",
    hostInstitution: "Universités publiques et privées de Turquie",
    deadline: "2026-11-30",
    coverageFr: "Exonération totale des frais de scolarité, billet d'avion A/R, allocation mensuelle, logement universitaire et assurance santé.",
    coverageEn: "Full tuition waiver, round-trip flight ticket, monthly stipend, university accommodation, and comprehensive health insurance.",
    coverageAr: "إعفاء كامل من الرسوم الدراسية، تذكرة طيران ذهاباً وإياباً، راتب شهري، سكن جامعي وتأمين صحي.",
    descriptionFr: "Programme d'excellence financé par le gouvernement turc ouvert aux bacheliers internationaux pour l'obtention d'un diplôme de Licence.",
    descriptionEn: "Government-funded scholarship program open to international high school graduates for full-time Bachelor degrees.",
    descriptionAr: "برنامج المنح الحكومية التركية الممول بالكامل للطلاب الدوليين لمتابعة دراسة البكالوريوس في مختلف التخصصات.",
    officialUrl: "https://www.turkiyeburslari.gov.tr/",
    isFeatured: true,
  },
  {
    id: "mext-japan-undergraduate-2026",
    slug: "bourse-gouvernement-japonais-mext-licence-2026",
    titleFr: "Bourse MEXT du Gouvernement Japonais - Programme Licence",
    titleEn: "Japanese Government MEXT Undergraduate Scholarship 2026-2027",
    titleAr: "منحة الحكومة اليابانية (MEXT) لدراسة البكالوريوس 2026-2027",
    category: "SCHOLARSHIP",
    degreeLevel: "UNDERGRADUATE",
    country: "Japon",
    hostInstitution: "Universités japonaises nationales et partenaires",
    deadline: "2026-10-15",
    coverageFr: "Prise en charge à 100 % des frais universitaires, billets d'avion internationaux aller-retour et allocation de vie mensuelle d'environ 120 000 JPY.",
    coverageEn: "100% tuition coverage, round-trip international airfare, and monthly living allowance of approx. 120,000 JPY.",
    coverageAr: "تغطية كاملة بنسبة 100٪ للرسوم الجامعية، تذاكر الطيران، وراتب معيشي شهري بقيمة تقارب 120,000 ين ياباني.",
    descriptionFr: "La bourse d'État japonaise MEXT permet aux étudiants internationaux d'intégrer une université au Japon après une année préparatoire linguistique.",
    descriptionEn: "The Japanese Government MEXT scholarship allows international applicants to enroll in Japanese universities including preparatory language year.",
    descriptionAr: "منحة وزارة التعليم اليابانية للطلاب المتميزين للدراسة في الجامعات اليابانية مع سنة تحضيرية للغة.",
    officialUrl: "https://www.studyinjapan.go.jp/en/planning/scholarship/",
    isFeatured: true,
  },
  {
    id: "csc-china-undergraduate-2026",
    slug: "bourse-gouvernement-chinois-csc-licence-2026",
    titleFr: "Bourse du Gouvernement Chinois (CSC) - Programme Bachelor",
    titleEn: "Chinese Government Scholarship (CSC) - Type A/B Undergraduate",
    titleAr: "منحة الحكومة الصينية (CSC) لدرجة البكالوريوس 2026-2027",
    category: "SCHOLARSHIP",
    degreeLevel: "UNDERGRADUATE",
    country: "Chine",
    hostInstitution: "Consortium des Universités d'Excellence Chinoises",
    deadline: "2026-12-15",
    coverageFr: "Frais de scolarité complets, hébergement universitaire gratuit, assurance médicale globale et allocation mensuelle de 2 500 CNY.",
    coverageEn: "Full tuition, free campus accommodation, comprehensive medical insurance, and 2,500 CNY monthly stipend.",
    coverageAr: "إعفاء كامل من الرسوم الدراسية، سكن مجاني، تأمين طبي شامل وراتب شهري قدره 2500 يوان صيني.",
    descriptionFr: "Programme officiel de coopération bilatérale du Conseil des bourses de Chine (CSC) ouvert à toutes les filières.",
    descriptionEn: "Official bilateral cooperation scholarship under the China Scholarship Council for science, engineering, business, and humanities.",
    descriptionAr: "المنحة الرسمية للتعاون الثنائي الممولة من الحكومة الصينية لمختلف التخصصات العلمية والهندسية والأدبية.",
    officialUrl: "https://www.campuschina.org/",
    isFeatured: true,
  },
  {
    id: "hungaricum-stipendium-bachelor-2026",
    slug: "bourse-stipendium-hungaricum-licence-2026",
    titleFr: "Bourse Stipendium Hungaricum - Licence en Hongrie",
    titleEn: "Stipendium Hungaricum Scholarship - Bachelor Programs 2026-2027",
    titleAr: "منحة الحكومة المجرية (Stipendium Hungaricum) للبكالوريوس 2026-2027",
    category: "SCHOLARSHIP",
    degreeLevel: "UNDERGRADUATE",
    country: "Hongrie",
    hostInstitution: "Universités publiques hongroises (ELTE, BME, Szeged, Debrecen)",
    deadline: "2027-01-15",
    coverageFr: "Études gratuites en anglais, subvention de logement mensuelle, couverture médicale européenne et allocation mensuelle.",
    coverageEn: "Tuition-free education in English, monthly dormitory contribution, European health insurance, and monthly living allowance.",
    coverageAr: "دراسة مجانية باللغة الإنجليزية، دعم شهري للسكن، تأمين صحي أوروبي وراتب شهري.",
    descriptionFr: "Programme gouvernemental hongrois offrant des cursus complets en anglais dans les établissements d'enseignement supérieur d'Europe centrale.",
    descriptionEn: "Hungarian government initiative offering fully accredited English-taught Bachelor degrees across central European universities.",
    descriptionAr: "مبادرة حكومية مجرية تتيح دراسة البكالوريوس باللغة الإنجليزية في كبرى جامعات وسط أوروبا.",
    officialUrl: "https://stipendiumhungaricum.hu/",
    isFeatured: true,
  },
  {
    id: "mastercard-foundation-bachelor-2026",
    slug: "bourses-mastercard-foundation-licence-afrique-2026",
    titleFr: "Bourses Mastercard Foundation - Premier Cycle & Leadership",
    titleEn: "Mastercard Foundation Scholars Program (Undergraduate) 2026-2027",
    titleAr: "منح مؤسسة ماستركارد لدرجة البكالوريوس والقيادة 2026-2027",
    category: "SCHOLARSHIP",
    degreeLevel: "UNDERGRADUATE",
    country: "International (Afrique, Europe, Amérique du Nord)",
    hostInstitution: "Réseau d'universités partenaires (UCT, KNUST, Ashesi, McGill, Sciences Po)",
    deadline: "2026-12-01",
    coverageFr: "Frais académiques complets, logement, livres, ordinateur portable, transport, soutien psychosocial et mentorat de leadership.",
    coverageEn: "Comprehensive financial support: tuition, living costs, books, laptop, transport, and transformative leadership coaching.",
    coverageAr: "دعم مالي كامل: الرسوم الدراسية، تكاليف المعيشة، الكتب، حاسوب محمول وتدريب قيادي.",
    descriptionFr: "Accompagne les jeunes africains talentueux issus de milieux modestes engagés dans le développement de leurs communautés.",
    descriptionEn: "Empowering bright young African leaders from economically disadvantaged backgrounds committed to community transformation.",
    descriptionAr: "برنامج موجه للشباب الأفارقة المتميزين من ذوي الدخل المحدود والملتزمين بإحداث أثر إيجابي في مجتمعاتهم.",
    officialUrl: "https://mastercardfdn.org/all/scholars/",
    isFeatured: true,
  },

  // --- NIVEAU MASTER ---
  {
    id: "erasmus-mundus-masters-2026",
    slug: "bourses-erasmus-mundus-master-union-europeenne-2026",
    titleFr: "Bourses Erasmus Mundus Joint Masters - Union Européenne",
    titleEn: "Erasmus Mundus Joint Masters Scholarships 2026-2027",
    titleAr: "منح إيراسموس موندوس لدرجة الماجستير المشترك - الاتحاد الأوروبي",
    category: "SCHOLARSHIP",
    degreeLevel: "MASTER",
    country: "Union Européenne (Multi-pays)",
    hostInstitution: "Consortiums universitaires européens d'excellence",
    deadline: "2027-01-31",
    coverageFr: "100 % des frais de scolarité, 1 400 € / mois d'indemnité de subsistance, billets d'avion internationaux et assurance multirisque.",
    coverageEn: "100% tuition coverage, €1,400/month living allowance, international travel costs, and full worldwide insurance.",
    coverageAr: "تغطية كاملة للمصاريف، راتب شهري بقيمة 1,400 يورو، تذاكر السفر وتأمين شامل.",
    descriptionFr: "Masters conjoints d'excellence permettant d'étudier dans au moins deux pays européens différents avec double ou triple diplôme.",
    descriptionEn: "High-level integrated Master programs studied across at least two European countries awarding joint or multiple degrees.",
    descriptionAr: "برامج ماجستير متميزة للدراسة في جامعتين أوروبيتين مختلفتين على الأقل مع شهادة مشتركة.",
    officialUrl: "https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/erasmus-mundus-joint-masters-scholarships",
    isFeatured: true,
  },
  {
    id: "chevening-uk-scholarships-2026",
    slug: "bourses-chevening-master-royaume-uni-2026",
    titleFr: "Bourses Chevening du Gouvernement Britannique - Master 1 An",
    titleEn: "Chevening UK Government Scholarships 2026-2027",
    titleAr: "منح شيفنينغ من الحكومة البريطانية لدراسة الماجستير 2026-2027",
    category: "SCHOLARSHIP",
    degreeLevel: "MASTER",
    country: "Royaume-Uni",
    hostInstitution: "Toutes les universités du Royaume-Uni (Oxford, Cambridge, LSE, UCL...)",
    deadline: "2026-11-05",
    coverageFr: "Frais de scolarité intégraux, allocation mensuelle de subsistance, vols aller-retour en classe économique et allocations de visa/départ.",
    coverageEn: "Full university tuition, monthly living allowance, economy return flights, and visa application grant.",
    coverageAr: "تغطية كاملة للمصاريف الدراسية، راتب شهري، تذاكر طيران ذهاب وعودة، وتكاليف التأشيرة.",
    descriptionFr: "Programme mondial du gouvernement britannique finançant les futurs leaders pour un Master d'un an dans toute université britannique.",
    descriptionEn: "UK government global scholarship programme funding future leaders for a one-year Master’s degree at any UK university.",
    descriptionAr: "البرنامج العالمي الرائد للحكومة البريطانية لتمويل قادة المستقبل لدراسة الماجستير لمدة عام واحد.",
    officialUrl: "https://www.chevening.org/scholarships/",
    isFeatured: true,
  },
  {
    id: "daad-epos-master-germany-2026",
    slug: "bourses-daad-epos-master-allemagne-2026",
    titleFr: "Bourses DAAD EPOS - Développement & Master en Allemagne",
    titleEn: "DAAD EPOS Scholarships for Development-Related Postgraduate Courses",
    titleAr: "منح DAAD EPOS لدراسة الماجستير المرتبط بالتنمية في ألمانيا",
    category: "SCHOLARSHIP",
    degreeLevel: "MASTER",
    country: "Allemagne",
    hostInstitution: "Universités publiques allemandes de recherche",
    deadline: "2026-10-31",
    coverageFr: "Allocation mensuelle de 934 €, couverture santé, subvention de voyage internationale et indemnité d'études annuelle.",
    coverageEn: "Monthly stipend of €934, health and accident insurance, travel allowance, and yearly study grant.",
    coverageAr: "راتب شهري بقيمة 934 يورو، تأمين صحي شامل، بدل سفر وبدل دراسة سنوي.",
    descriptionFr: "Offre aux jeunes diplômés et professionnels des pays en développement une formation de pointe dans les secteurs du développement durable.",
    descriptionEn: "Provides young professionals from developing nations with postgraduate training in sustainable development sectors.",
    descriptionAr: "فرصة للمهنيين الشباب للحصول على ماجستير في مجالات التنمية المستدامة والبيئة والتكنولوجيا.",
    officialUrl: "https://www2.daad.de/deutschland/stipendium/datenbank/en/21148-scholarship-database/",
    isFeatured: false,
  },

  // --- NIVEAU DOCTORAT / PHD ---
  {
    id: "fulbright-foreign-student-2026",
    slug: "programme-fulbright-doctorat-recherche-usa-2026",
    titleFr: "Programme Fulbright pour Étudiants Étrangers (USA) - Master & Doctorat",
    titleEn: "Fulbright Foreign Student Program (USA) 2026-2027",
    titleAr: "برنامج فولبرايت للدراسات العليا في الولايات المتحدة 2026-2027",
    category: "SCHOLARSHIP",
    degreeLevel: "PHD",
    country: "États-Unis",
    hostInstitution: "Universités américaines de recherche (R1 Universities)",
    deadline: "2026-10-15",
    coverageFr: "Frais de scolarité complets, allocation de subsistance, billets d'avion internationaux, assurance santé J-1 et accès au réseau mondial d'anciens.",
    coverageEn: "Full tuition, living stipend, round-trip international airfare, health benefit plan, and global alumni network access.",
    coverageAr: "تغطية كاملة للمصاريف، راتب شهري، تذاكر طيران، تأمين صحي، والوصول إلى شبكة الخريجين العالمية.",
    descriptionFr: "Programme d'excellence du Département d'État américain permettant aux chercheurs et étudiants africains de mener un cursus aux États-Unis.",
    descriptionEn: "Flagship international educational exchange program sponsored by the U.S. Department of State for advanced graduate study and research.",
    descriptionAr: "البرنامج الأبرز لوزارة الخارجية الأمريكية لدعم الدراسات العليا والأبحاث المتقدمة للطلاب الدوليين.",
    officialUrl: "https://foreign.fulbrightonline.org/",
    isFeatured: true,
  },

  // --- FONDS D'URGENCE & SECOURS ---
  {
    id: "ava-emergency-fund-2026",
    slug: "fonds-urgence-sociale-solidarite-etudiante-ava-2026",
    titleFr: "Fonds d'Urgence Sociale & Solidarité Étudiante AVA",
    titleEn: "AVA Social Emergency & Student Solidarity Relief Fund",
    titleAr: "صندوق الطوارئ الاجتماعية والتضامن الطلابي - تحالف AVA",
    category: "EMERGENCY_FUND",
    degreeLevel: "ALL",
    country: "Afrique (Zone d'intervention AVA)",
    hostInstitution: "Alliance des Visionnaires Africains (Comité de Crise)",
    deadline: "2026-12-31",
    coverageFr: "Aide financière d'urgence, assistance administrative, soutien aux étudiants déplacés ou en rupture de scolarité.",
    coverageEn: "Direct emergency financial grants, legal/administrative guidance, and support for displaced students.",
    coverageAr: "مساعدات مالية طارئة، إرشاد إداري ودعم عاجل للطلاب في مناطق الأزمات والنزوح.",
    descriptionFr: "Cellule de solidarité directe mise en place par AVA pour répondre aux urgences humanitaires et éducatives des étudiants africains.",
    descriptionEn: "Direct emergency relief cell established by AVA to support vulnerable African youth facing educational interruptions.",
    descriptionAr: "خلية التدخل الإنساني والتعليمي المباشرة لدعم الطلاب المتأثرين بالأزمات في أفريقيا.",
    officialUrl: "https://africanvisionaries.org/contact",
    isFeatured: true,
  },
];