export interface TeamRoleItem {
  id: string;
  category: "EXECUTIVE_COUNCIL" | "SECRETARIAT" | "REGIONAL_REPS" | "SPECIAL_REPS";
  roleTitleFr: string;
  roleTitleEn: string;
  roleTitleAr: string;
  name: string;
  bioFr: string;
  bioEn: string;
  bioAr: string;
  photoUrl?: string;
}

export const officialTeamStructure: TeamRoleItem[] = [
  { id: "exec-pres", category: "EXECUTIVE_COUNCIL", roleTitleFr: "Président", roleTitleEn: "President", roleTitleAr: "الرئيس", name: "[Nom à renseigner]", bioFr: "Porte la vision de l'Alliance, garant des valeurs statutaires et des relations institutionnelles.", bioEn: "Carries the vision of the Alliance, guarantor of statutory values and institutional relations.", bioAr: "يقود رؤية التحالف، ضامن للقيم الأساسية والعلاقات المؤسسية.", photoUrl: "/images/team/president.jpg" },
  { id: "exec-vp-1", category: "EXECUTIVE_COUNCIL", roleTitleFr: "Vice-Président (Région Nord & Ouest)", roleTitleEn: "Vice-President (North & West)", roleTitleAr: "نائب الرئيس (الشمال والغرب)", name: "[Nom à renseigner]", bioFr: "Coordination et supervision des activités régionales et partenariats territoriaux.", bioEn: "Coordination and oversight of regional activities and territorial partnerships.", bioAr: "تنسيق والإشراف على الأنشطة الإقليمية والشراكات المحلية.", photoUrl: "/images/team/vp-north-west.jpg" },
  { id: "exec-vp-2", category: "EXECUTIVE_COUNCIL", roleTitleFr: "Vice-Président (Région Centre & Est)", roleTitleEn: "Vice-President (Central & East)", roleTitleAr: "نائب الرئيس (الوسط والشرق)", name: "[Nom à renseigner]", bioFr: "Coordination des programmes d'urgence et d'accompagnement de la jeunesse.", bioEn: "Coordination of emergency programs and youth empowerment initiatives.", bioAr: "تنسيق برامج الطوارئ ومبادرات تمكين الشباب.", photoUrl: "/images/team/vp-central-east.jpg" },
  { id: "exec-vp-3", category: "EXECUTIVE_COUNCIL", roleTitleFr: "Vice-Président (Région Australe & Diaspora)", roleTitleEn: "Vice-President (Southern & Diaspora)", roleTitleAr: "نائب الرئيس (الجنوب والمهجر)", name: "[Nom à renseigner]", bioFr: "Coordination régionale et mobilisation des talents de la diaspora africaine.", bioEn: "Regional coordination and mobilization of African diaspora talents.", bioAr: "التنسيق الإقليمي وحشد كفاءات المهجر الأفريقي.", photoUrl: "/images/team/vp-south-diaspora.jpg" },
  { id: "exec-sg", category: "EXECUTIVE_COUNCIL", roleTitleFr: "Secrétaire Général", roleTitleEn: "Secretary-General", roleTitleAr: "الأمين العام", name: "[Nom à renseigner]", bioFr: "Gestion opérationnelle, administration quotidienne du siège et coordination du secrétariat.", bioEn: "Operational management, daily headquarters administration, and secretariat coordination.", bioAr: "الإدارة التشغيلية، التسيير اليومي للمقر وتنسيق الأمانة العامة.", photoUrl: "/images/team/secretary-general.jpg" },
  { id: "exec-deputy-sg", category: "EXECUTIVE_COUNCIL", roleTitleFr: "Secrétaire Général Adjoint", roleTitleEn: "Deputy Secretary-General", roleTitleAr: "نائب الأمين العام", name: "[Nom à renseigner]", bioFr: "Appui à la gestion opérationnelle et coordination interne des départements.", bioEn: "Support to operational management and internal department coordination.", bioAr: "دعم التسيير العملياتي والتنسيق الداخلي بين الأقسام.", photoUrl: "/images/team/deputy-sg.jpg" },
  { id: "exec-treasurer", category: "EXECUTIVE_COUNCIL", roleTitleFr: "Trésorier Général", roleTitleEn: "Treasurer", roleTitleAr: "أمين الصندوق العام", name: "[Nom à renseigner]", bioFr: "Gestion financière, transparence budgétaire, audits et contrôle des ressources.", bioEn: "Financial management, budget transparency, audits, and resource oversight.", bioAr: "الإدارة المالية، الشفافية، التدقيق ومراقبة الموارد.", photoUrl: "/images/team/treasurer.jpg" },
  { id: "sec-prog", category: "SECRETARIAT", roleTitleFr: "Directeur des Programmes & Réponses d'Urgence", roleTitleEn: "Program & Emergency Response Director", roleTitleAr: "مدير البرامج والاستجابة للطوارئ", name: "[Nom à renseigner]", bioFr: "Déploiement des réponses rapides, bourses d'études et initiatives communautaires.", bioEn: "Deployment of rapid responses, scholarships, and community initiatives.", bioAr: "تنفيذ برامج الاستجابة السريعة والمنح والمبادرات المجتمعية.", photoUrl: "/images/team/program-director.jpg" },
  { id: "sec-part", category: "SECRETARIAT", roleTitleFr: "Directeur des Partenariats & Mobilisation des Ressources", roleTitleEn: "Partnerships & Resource Mobilization Director", roleTitleAr: "مدير الشراكات وتعبئة الموارد", name: "[Nom à renseigner]", bioFr: "Développement des alliances stratégiques, bailleurs et coopérations internationales.", bioEn: "Strategic alliance development, donors, and international cooperation.", bioAr: "تطوير التحالفات الاستراتيجية والمانحين والتعاون الدولي.", photoUrl: "/images/team/partnerships-director.jpg" },
  { id: "sec-comm", category: "SECRETARIAT", roleTitleFr: "Directeur de la Communication & Plaidoyer", roleTitleEn: "Communications & Advocacy Director", roleTitleAr: "مدير الاتصال والمناصرة", name: "[Nom à renseigner]", bioFr: "Veille numérique, rayonnement médiatique, publications et sensibilisation.", bioEn: "Digital monitoring, media relations, publications, and awareness campaigns.", bioAr: "الرصد الرقمي، العلاقات الإعلامية، النشر والتوعية المجتمعية.", photoUrl: "/images/team/communication-director.jpg" },
  { id: "rep-north", category: "REGIONAL_REPS", roleTitleFr: "Représentant Régional - Afrique du Nord", roleTitleEn: "Regional Representative - North Africa", roleTitleAr: "الممثل الإقليمي - شمال أفريقيا", name: "[Nom à renseigner]", bioFr: "Point focal et coordination des comités pays d'Afrique du Nord.", bioEn: "Focal point and coordination of North African country committees.", bioAr: "نقطة الاتصال وتنسيق لجان دول شمال أفريقيا.", photoUrl: "/images/team/rep-north.jpg" },
  { id: "rep-west", category: "REGIONAL_REPS", roleTitleFr: "Représentant Régional - Afrique de l'Ouest", roleTitleEn: "Regional Representative - West Africa", roleTitleAr: "الممثل الإقليمي - غرب أفريقيا", name: "[Nom à renseigner]", bioFr: "Point focal et coordination des comités pays d'Afrique de l'Ouest.", bioEn: "Focal point and coordination of West African country committees.", bioAr: "نقطة الاتصال وتنسيق لجان دول غرب أفريقيا.", photoUrl: "/images/team/rep-west.jpg" },
  { id: "rep-central", category: "REGIONAL_REPS", roleTitleFr: "Représentant Régional - Afrique Centrale", roleTitleEn: "Regional Representative - Central Africa", roleTitleAr: "الممثل الإقليمي - وسط أفريقيا", name: "[Nom à renseigner]", bioFr: "Point focal et coordination des comités pays d'Afrique Centrale.", bioEn: "Focal point and coordination of Central African country committees.", bioAr: "نقطة الاتصال وتنسيق لجان دول وسط أفريقيا.", photoUrl: "/images/team/rep-central.jpg" },
  { id: "rep-east", category: "REGIONAL_REPS", roleTitleFr: "Représentant Régional - Afrique de l'Est", roleTitleEn: "Regional Representative - East Africa", roleTitleAr: "الممثل الإقليمي - شرق أفريقيا", name: "[Nom à renseigner]", bioFr: "Point focal et coordination des comités pays d'Afrique de l'Est.", bioEn: "Focal point and coordination of East African country committees.", bioAr: "نقطة الاتصال وتنسيق لجان دول شرق أفريقيا.", photoUrl: "/images/team/rep-east.jpg" },
  { id: "rep-south", category: "REGIONAL_REPS", roleTitleFr: "Représentant Régional - Afrique Australe", roleTitleEn: "Regional Representative - Southern Africa", roleTitleAr: "الممثل الإقليمي - جنوب أفريقيا", name: "[Nom à renseigner]", bioFr: "Point focal et coordination des comités pays d'Afrique Australe.", bioEn: "Focal point and coordination of Southern African country committees.", bioAr: "نقطة الاتصال وتنسيق لجان دول الجنوب الأفريقي.", photoUrl: "/images/team/rep-south.jpg" },
  { id: "rep-youth-1", category: "SPECIAL_REPS", roleTitleFr: "Représentant de la Jeunesse (Affaires Académiques)", roleTitleEn: "Youth Representative (Academic Affairs)", roleTitleAr: "ممثل الشباب (الشؤون الأكاديمية)", name: "[Nom à renseigner]", bioFr: "Mobilisation des étudiants et plaidoyer pour l'accès aux bourses d'études.", bioEn: "Student mobilization and advocacy for equal access to scholarships.", bioAr: "تعبئة الطلاب والمناصرة لتيسير الحصول على المنح الدراسية.", photoUrl: "/images/team/rep-youth-1.jpg" },
  { id: "rep-youth-2", category: "SPECIAL_REPS", roleTitleFr: "Représentant de la Jeunesse (Innovation & Leadership)", roleTitleEn: "Youth Representative (Innovation & Leadership)", roleTitleAr: "ممثل الشباب (الابتكار والقيادة)", name: "[Nom à renseigner]", bioFr: "Encadrement des initiatives jeunes, mentorat et entrepreneuriat social.", bioEn: "Youth initiative mentoring and community social entrepreneurship.", bioAr: "تأطير المبادرات الشبابية والإرشاد وريادة الأعمال المجتمعية.", photoUrl: "/images/team/rep-youth-2.jpg" },
  { id: "rep-gender", category: "SPECIAL_REPS", roleTitleFr: "Représentant Égalité des Genres & Droits des Femmes", roleTitleEn: "Gender Equality & Women's Rights Representative", roleTitleAr: "ممثل المساواة بين الجنسين وحقوق المرأة", name: "[Nom à renseigner]", bioFr: "Intégration transversale de l'égalité et protection des personnes vulnérables.", bioEn: "Systematic integration of equality and protection of vulnerable groups.", bioAr: "الإدماج الشامل للمساواة وحماية الفئات الهشة في حالات الطوارئ.", photoUrl: "/images/team/rep-gender.jpg" },
];
