export interface TeamRoleItem {
  id: string;
  category: "EXECUTIVE_COUNCIL" | "SECRETARIAT" | "REGIONAL_REPS" | "SPECIAL_REPS";
  roleTitleFr: string;
  roleTitleEn: string;
  roleTitleAr: string;
  name: string;
  bioFr: string;
  bioEn: string;
  bioAr: string;
  photoUrl?: string;
}

export const officialTeamStructure: TeamRoleItem[] = [
  {
    id: "exec-pres",
    category: "EXECUTIVE_COUNCIL",
    roleTitleFr: "Présidente du Conseil Exécutif",
    roleTitleEn: "President of the Executive Council",
    roleTitleAr: "رئيسة المجلس التنفيذي",
    name: "Présidente AVA",
    bioFr: "Porte la vision de l'Alliance, veille au respect des valeurs statutaires et pilote les relations de haut niveau.",
    bioEn: "Leads the vision of the Alliance, ensures adherence to statutory values, and guides high-level partnerships.",
    bioAr: "تقود رؤية التحالف، وتضمن احترام القيم الأساسية وترعى الشراكات المؤسسية.",
    photoUrl: "/images/team/president.jpg",
  },
  {
    id: "exec-vp-ouest",
    category: "EXECUTIVE_COUNCIL",
    roleTitleFr: "Vice-Président (Région Ouest & Sahel)",
    roleTitleEn: "Vice-President (West & Sahel)",
    roleTitleAr: "نائب الرئيس (الغرب والساحل)",
    name: "Vice-Président AVA",
    bioFr: "Coordination et impulsion des dynamiques régionales d'Afrique de l'Ouest, gouvernance territoriale et plaidoyer jeunesse.",
    bioEn: "Coordination and steering of West African regional dynamics, territorial governance, and youth advocacy.",
    bioAr: "تنسيق ودفع الديناميكيات الإقليمية لغرب أفريقيا والساحل، والحوكمة المحلية ومناصرة الشباب.",
    photoUrl: "/images/team/vp-ouest.jpg",
  },
  {
    id: "exec-vp-centre",
    category: "EXECUTIVE_COUNCIL",
    roleTitleFr: "Vice-Président (Région Centre & Ouest)",
    roleTitleEn: "Vice-President (Central & West)",
    roleTitleAr: "نائب الرئيس (الوسط والغرب)",
    name: "Vice-Président AVA",
    bioFr: "Supervision des points focaux territoriaux et coordination des programmes de résilience régionale.",
    bioEn: "Oversight of territorial focal points and regional resilience program coordination.",
    bioAr: "الإشراف على نقاط الاتصال المحلية وتنسيق برامج الصمود الإقليمية.",
    photoUrl: "/images/team/vp-centre.jpg",
  },
  {
    id: "exec-vp-est",
    category: "EXECUTIVE_COUNCIL",
    roleTitleFr: "Vice-Présidente (Région Est & Australe)",
    roleTitleEn: "Vice-President (East & Southern)",
    roleTitleAr: "نائبة الرئيس (الشرق والجنوب)",
    name: "Vice-Présidente AVA",
    bioFr: "Coordination des dynamiques communautaires, mobilisation de la jeunesse et suivi des partenariats régionaux.",
    bioEn: "Coordination of community dynamics, youth mobilization, and regional partnerships monitoring.",
    bioAr: "تنسيق الديناميكيات المجتمعية وتعبئة الشباب ومتابعة الشراكات الإقليمية.",
    photoUrl: "/images/team/vp-est.jpg",
  },
  {
    id: "exec-sg",
    category: "EXECUTIVE_COUNCIL",
    roleTitleFr: "Secrétaire Général",
    roleTitleEn: "Secretary-General",
    roleTitleAr: "الأمين العام",
    name: "Secrétaire Général AVA",
    bioFr: "Supervision opérationnelle, coordination administrative et gouvernance du secrétariat.",
    bioEn: "Operational supervision, administrative coordination, and secretariat governance.",
    bioAr: "الإشراف التشغيلي، والتنسيق الإداري وحوكمة الأمانة العامة.",
    photoUrl: "/images/team/secretaire.jpg",
  },
  {
    id: "exec-tresorier",
    category: "EXECUTIVE_COUNCIL",
    roleTitleFr: "Trésorière Générale",
    roleTitleEn: "General Treasurer",
    roleTitleAr: "أمينة الصندوق العامة",
    name: "Trésorière AVA",
    bioFr: "Gestion financière, transparence budgétaire, contrôle des comptes et audits institutionnels.",
    bioEn: "Financial management, budget transparency, account auditing, and institutional control.",
    bioAr: "الإدارة المالية، والشفافية في الميزانية، وتدقيق الحسابات والرقابة المؤسسية.",
    photoUrl: "/images/team/tresorier.jpg",
  },
  {
    id: "sec-dir-gen",
    category: "SECRETARIAT",
    roleTitleFr: "Directeur des Opérations",
    roleTitleEn: "Operations Director",
    roleTitleAr: "مدير العمليات",
    name: "Directeur des Opérations",
    bioFr: "Conduite et suivi des déploiements logistiques, projets prioritaires et réponses d'urgence sur le terrain.",
    bioEn: "Leading logistical deployment, priority projects, and on-ground emergency response.",
    bioAr: "قيادة ومتابعة العمليات اللوجستية والمشاريع ذات الأولوية والاستجابة الميدانية.",
    photoUrl: "/images/team/directeur.jpg",
  },
  {
    id: "sec-part",
    category: "SECRETARIAT",
    roleTitleFr: "Directeur des Partenariats & Mobilisation des Ressources",
    roleTitleEn: "Partnerships & Resource Mobilization Director",
    roleTitleAr: "مدير الشراكات وتعبئة الموارد",
    name: "Directeur des Partenariats",
    bioFr: "Développement des alliances institutionnelles, bailleurs internationaux et accords de coopération.",
    bioEn: "Development of institutional alliances, international donors, and cooperation agreements.",
    bioAr: "تطوير التحالفات المؤسسية والتعاون مع الجهات المانحة الدولية.",
    photoUrl: "/images/team/partnerships-director.jpg",
  },
  {
    id: "sec-formateur",
    category: "SECRETARIAT",
    roleTitleFr: "Responsable Formation & Développement des Compétences",
    roleTitleEn: "Capacity Building & Training Lead",
    roleTitleAr: "مسؤول التدريب وتنمية المهارات",
    name: "Responsable Formation",
    bioFr: "Encadrement pédagogique, conception des masterclass et renforcement des capacités des jeunes.",
    bioEn: "Pedagogical supervision, masterclass design, and youth capacity building.",
    bioAr: "التأطير التربوي، وتصميم الورش التدريبية وبناء قدرات الشباب.",
    photoUrl: "/images/team/formateur.jpg",
  },
  {
    id: "pole-bourses",
    category: "SPECIAL_REPS",
    roleTitleFr: "Responsable du Pôle Bourses & Opportunités Académiques",
    roleTitleEn: "Scholarships & Academic Opportunities Lead",
    roleTitleAr: "مسؤول قطاع المنح والفرص الأكاديمية",
    name: "Responsable Pôle Bourses",
    bioFr: "Veille, vérification stricte et accompagnement des candidats vers les bourses internationales.",
    bioEn: "Monitoring, strict verification, and applicant guidance for international scholarships.",
    bioAr: "رصد والتحقق الدقيق من المنح الدولية وإرشاد المتقدمين.",
    photoUrl: "/images/team/resp-bourses.jpg",
  },
  {
    id: "pole-cyber",
    category: "SPECIAL_REPS",
    roleTitleFr: "Responsable Veille Numérique & Cybersécurité",
    roleTitleEn: "Digital Monitoring & Cybersecurity Lead",
    roleTitleAr: "مسؤول الرصد الرقمي والأمن السيبراني",
    name: "Responsable Pôle Numérique",
    bioFr: "Sécurisation des plateformes, lutte contre la désinformation et veille technologique.",
    bioEn: "Platform security, anti-disinformation efforts, and technological monitoring.",
    bioAr: "حماية المنصات، مكافحة التضليل والرصد التقني المستمر.",
    photoUrl: "/images/team/resp-cyber.jpg",
  },
  {
    id: "pole-urgences",
    category: "SPECIAL_REPS",
    roleTitleFr: "Responsable Réponse aux Urgences Sociales",
    roleTitleEn: "Social Emergency Response Lead",
    roleTitleAr: "مسؤول الاستجابة للطوارئ الاجتماعية",
    name: "Responsable Pôle Urgences",
    bioFr: "Coordination des cellules de crise, évaluation des besoins communautaires et secours rapides.",
    bioEn: "Crisis unit coordination, community needs assessment, and rapid assistance.",
    bioAr: "تنسيق خلايا الأزمة، وتقييم الاحتياجات المجتمعية والتدخل العاجل.",
    photoUrl: "/images/team/resp-urgences.jpg",
  },
  {
    id: "rep-gender",
    category: "SPECIAL_REPS",
    roleTitleFr: "Représentante Égalité des Genres & Inclusion",
    roleTitleEn: "Gender Equality & Inclusion Representative",
    roleTitleAr: "ممثلة المساواة والشمول",
    name: "Nada Idris",
    bioFr: "Plaidoyer pour l'accès équitable des femmes et des jeunes filles aux opportunités mondiales.",
    bioEn: "Advocacy for equitable access of women and young girls to global opportunities.",
    bioAr: "المناصرة لتعزيز تكافؤ الفرص وتمكين المرأة والفتيات في البرامج الدولية.",
    photoUrl: "/images/team/nada-idris.jpg",
  },
];
